### ISSUE TITLE
Not receiving the callback from enqueueMapBuffer

### ISSUE THREAD

**Issue by metabench** [unbornchikken/NOOOCL#1]
I'm new to OpenCL. I've tried following the code from the readme and the tests, but I'm not getting a callback when calling `enqueueMapBuffer`. The promise exists, but no callback ever gets called, and I use the syntax `.then(function(){...})`.

I think some really simple examples would help with understanding how to use it, far simpler than a particle simulation. Being able to add two vectors of numbers together would be helpful to get going.

Is there a way to use `enqueueMapBuffer` asynchronously, using callbacks rather than promises?

**Comment by unbornchikken** [comment]
Thanks for the feedback! I'm trying to get some time to add some basic examples to the readme. Until then, please do not hesitate to put your code there, I will help you to make it work for sure.

Yust for the record, promises are always asynchronous. Those like callbacks encapsulated to an object to have the ability to make them composable. You can use a promise by the good old node way:

```js
...promise.nodeify(function(err, result) {
  // Whoa, finally a callback!
})
```

**Comment by metabench** [comment]
I don't get the time to document everything either, within my own project. I'm very much in favour of developers publishing what they have, even if it's not ready to be used. I think having OpenCL bindings in node is important, and I'm keen on helping to improve this project. This project looks as though the engineering is solid, but it's particularly hard to get started with because of the sparse documentation.

I have not actually got any OpenCL to run using this project. I did get OpenCL running through a C++ addon using https://www.olcf.ornl.gov/tutorials/opencl-vector-addition/, and have now modified that somewhat. Would everything there translate OK using NOOOCL?

The way that I think I'd proceed to get NOOOCL to work, so I could document it, would be to modify a test file so that it just executes some code. I did not get to actually run the tests though, what do I use to do that?

If you were to provide me with just one example of NOOOCL just doing something simple (with no test code) that would be a great help, but if you don't have time for that soon then I'd need to change some of the test code to only carry out the OpenCL.

I'm also interested in what patterns would make for efficient calling of OpenCL. With the current example I'm working on in C++ it compiles the kernel each time it's called. I think I could have it cache a whole load of things (particularly the compiled kernel) in order to actually run quickly. I'd like to develop and showcase patterns that enable OpenCL to be used efficiently in a variety of use cases.

Also, I think some simplified  wrappers would be of great help. That sounds like it should probably be outside of this project's scope, but it's something we could work together on if you are interested.

Are you still lacking a GPU that supports OpenCL 2.0? And if you were given one, would you have the time to work on the 2.0 API any time soon?

**Comment by unbornchikken** [comment]
Your kind words was more than enough to inspire me to release a complete example project. Please take a look at the new readme.

Code, example or documentation contributions are welcome of course! Please do not hesitate to PR anything that you got, I'll review an merge them ASAP.

Regarding caching of the compiled kernel binaries, it is of course supported in NOOOCL. You can query compiled program binaries, and can make program from them later, which process is much faster than to compile them from source. See: https://github.com/unbornchikken/NOOOCL#build

I think abstractions of NOOOCL library are already simplified compared to native bindings, so simplify them more is kinda out of scope. But I can imagine a library on top of NOOOCL to do it (like [OpenCLTemplate for .NET](http://www.cmsoft.com.br/downloads/opencltemplate-dll/)).

As soon as I get a capable card, I'm gonna do OCL 2.0 support for NOOOCL. It's not too hard, just kdiff cl.h 1.2 vs cl.h 2.0, then write some ffi binding code, and done. Right now getting a new card is on low  priority on my family budget, I have two small child you know. :)

**Comment by unbornchikken** [comment]
I'm still waiting for your sample code describing the original issue regarding enqueueMapBuffer. Please put it there, I can help you with this for sure.

**Comment by unbornchikken** [comment]
We've handled this issue privately. No work have to be done at NOOOCL side.
