### ISSUE TITLE
Feature: manual gpu memory free

### ISSUE THREAD

**Issue by vird** [unbornchikken/NOOOCL#15]
At this moment I can easily crash my app with overmapping gpu device from different code points. GC can be slower than I need.
I think CLBuffer.prototype.free method should call clReleaseMemObject.

**Comment by unbornchikken** [comment]
It does: https://github.com/unbornchikken/NOOOCL/blob/master/lib/clMemory.js#L48

The method that you seek is actually called as 'release' not 'free': https://github.com/unbornchikken/NOOOCL/blob/master/lib/clWrapper.js#L129
