### ISSUE TITLE
How to choose the very opencl instance on the host?

### ISSUE THREAD

**Issue by march1993** [unbornchikken/NOOOCL#16]
I'm running nooocl no an intel bay-trail board. There are several opencl instances, intel opencl sdk and beignet opencl driver.  But it seems that nooocl only uses default intel opencl sdk. How can I choose to use beignet?

**Comment by unbornchikken** [comment]
Please find an example there: https://github.com/unbornchikken/NOOOCL/blob/master/tests/testHelpers.js#L38

Basically you can query platforms (= SDKs) and all of supported devices of them (like AMD APP CPU, AMD APP GPU, etc.).

**Comment by march1993** [comment]
Do you means that libopencl.so provided by Intel can use the CL lib from AMD?

**Comment by unbornchikken** [comment]
I mean if you're on Windows or you have OpenCL ICD installed on Linux, you can enumerate all SDK-s by calling host.getPlatforms().

**Comment by march1993** [comment]
ok
