### ISSUE TITLE
Calling same kernel several times may result in corrupt output.

### ISSUE THREAD

**Issue by march1993** [unbornchikken/NOOOCL#17]
codes like
```
var kernel = program.createKernel(kernel_name)
for (var i = 0; i < 100; i++) {
    kernel.setArg(0, /* ... */);
    kernel.setArg(1, /* ... */);

    queue.enqueueNDRangeKernel(kernel, ...);
}
```
may produce unexpected results.

see [calling the same kernel object multiple times](https://forums.khronos.org/showthread.php/5810-calling-the-same-kernel-object-multiple-times)

**Comment by unbornchikken** [comment]
So?

**Comment by march1993** [comment]
does it mean that I should create several kernels for avoiding wrong results?

**Comment by unbornchikken** [comment]
Yup. But you gotta call kernel.release() manually between setups to avoid unnecessary resource consuming.

**Comment by march1993** [comment]
okay
