### ISSUE TITLE
Hanges on Intel hd 530 graphics 

### ISSUE THREAD

**Issue by jeremydiviney** [unbornchikken/NOOOCL#18]
Setup:

Windows 10
node v4.4.3
Latest Intel OpenCL drivers
Intel HD 530 graphics

The tests and examples and any other small nooocl program never gets a response back from the enqueueReadBuffer call after a kernel is launched.

I have successfully tested on gtx 970, and intel cpu, but my intel hd 530 graphics don't ever produce a response after the kernel is launched, just hangs the node process waiting for the callback.  Seems similar in nature to #2 

One interesting thing to note: if the node process is run from "Generate New Session" from the opencl tools in visual studio, it does successfully execute the node application.  not sure what the difference is.

**Comment by arjunmehta** [comment]
This also happens in MacOS. I've tried Node 7.2.1 with Intel Iris 5100 Graphics.
Just hangs during `CLBuffer` test.

If I comment out GPU testing, it works when testing on the CPU. Willing to help in debugging. May have something to do with buffer size?

**Comment by arjunmehta** [comment]
[Output from `clinfo` on my Late 2013 13" Macbook Pro](https://github.com/unbornchikken/NOOOCL/files/653837/clinfo.txt)

**Comment by unbornchikken** [comment]
Please try v0.12.4+, I believe that's got fixed. Open up this issue if still presents at you side.

**Comment by arjunmehta** [comment]
Yes works on my mac now! A+
