### ISSUE TITLE
OpenCL Error Code: -1001 Type: UNKNOWN

### ISSUE THREAD

**Issue by ConsciousCode** [unbornchikken/NOOOCL#19]
For versions 1.1 and 1.2, calling `getPlatforms()` or accessing `platformsCount ` result in the following error:

> CLError: OpenCL Error Code: -1001 Type: UNKNOWN
>     at CL11.checkError (/home/consciouscode/node_modules/nooocl/lib/cl11.js:712:19)
>     at CLHost.Object.defineProperties._nPlatformsCount.get (/home/consciouscode/node_modules/nooocl/lib/clHost.js:77:21)
>     at CLHost.Object.defineProperties.platformsCount.get (/home/consciouscode/node_modules/nooocl/lib/clHost.js:85:24)
> 
> (same thing...)
> (/home/consciouscode/node_modules/nooocl/lib/clHost.js:77:21)
>     at CLHost.getPlatforms (/home/consciouscode/node_modules/nooocl/lib/clHost.js:111:21)

I'm not sure if this is a problem with my build or libOpenCL or what, but I was hoping you might have some answers.

**Comment by unbornchikken** [comment]
I'ts an OpenCL error, not NOOOCL one. See this: http://stackoverflow.com/questions/4959621/error-1001-in-clgetplatformids-call
