### ISSUE TITLE
Typings for NOOOCL (@types/nooocl)

### ISSUE THREAD

**Issue by rk-7** [unbornchikken/NOOOCL#30]
Can we have typings for NOOOCL (like @types/NOOOCL)? This will help us use Typescript which is more convenient.

**Comment by unbornchikken** [comment]
Nope. I'm not a big fan of Typescipt, so I don't wanna create and mantain typings. But, as always, I'm ready to accept anything that imporoves my Github projects, so if you make a PR, I get it to land for sure.
