### ISSUE TITLE
Error: Cannot find module 'ffi-io'

### ISSUE THREAD

**Issue by vird** [unbornchikken/NOOOCL#4]
Error: Cannot find module 'ffi-io'

just
require('nooocl')

nooocl@0.10.0 node_modules/nooocl
├── bluebird@2.9.34
├── ref-struct@1.0.1 (debug@2.2.0)
├── ref-array@1.1.1 (array-index@0.1.1, debug@2.2.0)
├── lodash@3.10.1
├── weak@0.4.1 (bindings@1.2.1, nan@1.8.4)
└── ffi@1.3.2 (bindings@1.2.1, debug@2.2.0, nan@1.9.0)

**Comment by vird** [comment]
replacing ffi-io -> ffi in sources causes vecAdd example not finish node process properly (all calculations done, all stdout present but it's wait something)

**Comment by unbornchikken** [comment]
Try 0.10.1.
